before_script:
  - "psql -c 'create database ananta_test;' -U ananta"
language: ruby
rvm:
  - 1.9.3
bundler_args: "--without development production staging sandbox"
notifications:
  email: false
  # TODO: Setup ananta-dev
  # irc:	
  #   on_success: change
  #   on_failure: always
  #   channels:
  #     - "irc.freenode.org#ananta-dev"