language: ruby
rvm:
  - 1.9.3
before_bundler: "gem intsall bundler --pre" # TODO: rm when bundler officialy hits 1.4.0
bundler_args: "--without development production staging sandbox"
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - "psql -c 'create database myapp_test;' -U postgres"
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
notifications:
  email: false
  # TODO: Setup ananta-dev
  # irc:	
  #   on_success: change
  #   on_failure: always
  #   channels:
  #     - "irc.freenode.org#ananta-dev"
# env: 
#   - DB=postgres