language: ruby
before_script:
  # - "mysql -e 'create database myapp_test;'"
  - "psql -c 'create database myapp_test;' -U postgres"
env:
  # - DB=sqlite
  # - DB=mysql
  - DB=postgres
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  
# TODO: setup ci@ananta.io and uncomment these lines
# notifications:
#   email:
#     - ci@ananta.io
  # TODO: setup irc
  # irc:
  #   - "irc.freenode.org#ananta"